# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Ruthy Yao
description: "Hi I'm Ruthy, and I'm passionate about translating data into actional insights.  My self-learned project portfolio has a wide range of interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science / Data Analytics <span style="color:#f58506"> Portfolio </span>
location: "Sydney, AU"
avatar_image: /img/RY_profile_photo Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/ruthy-yao-b3258b25/" # Add your linkedln handle
github: "https://github.com/RuthyYao"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

